defaults:
  - dataset: ABIDE
  - model: bnt
  - optimizer: adam
  - training: basic_supervised #debug 
  - datasz: 100p
  - preprocess: inclass_node_mixup #default
  - _self_ 

repeat_time: 5
log_path: result
experiment_name: BNTransformer_ABIDE
seed: 42

project: DLBenchmarking