defaults:
  - dataset: EOEC
  - model: graph_transformer
  - optimizer: adam
  - training: basic_supervised
  - datasz: 100p
  - preprocess: inclass_node_mixup

repeat_time: 5
log_path: result
experiment_name: GraphTransformerExperiments
seed: 42

project: DLBenchmarking