defaults:
  - dataset: ABIDE
  - model: bnt
  - optimizer: adam
  - training: debug
  - datasz: 100p
  - preprocess: inclass_node_mixup

repeat_time: 2
log_path: result
experiment_name: BNTTransformerExperiments
seed: 42

project: DLBenchmarking