defaults:
  - dataset: ABIDE
  - model: brainnetcnn # mlp2hl, fbnetgen, bnt, transformer
  - optimizer: adam
  - training: basic_supervised
  - datasz: 100p
  - preprocess: inclass_node_mixup #default
  - _self_ 

repeat_time: 4
log_path: result
experiment_name: BrainNetCNN_ABIDE
seed: 42

project: DLBenchmarking