defaults:
  - dataset: ABIDE
  - model: meanmlp # mlp2hl, fbnetgen, bnt, transformer
  - optimizer: adam
  - training: basic_supervised
  - datasz: 100p
  - preprocess:  default #inclass_node_mixup  - 0.5 score
  - _self_ 

repeat_time: 4
log_path: result
experiment_name: MeanMLP_ABIDE
seed: 42

project: DLBenchmarking