defaults:
  - dataset: ABIDE
  - model: meanmlp # mlp2hl, fbnetgen, bnt, transformer
  - optimizer: adam
  - training: basic_supervised
  - datasz: 100p
  - preprocess: default

repeat_time: 5
log_path: result
experiment_name: MeanMLPexperiments
seed: 42

project: DLBenchmarking