defaults:
  - dataset: ABIDE
  - model: bnt
  - optimizer: adam
  - training: debug #basic_supervised
  - datasz: 30p
  - preprocess: inclass_node_mixup #default
  - _self_ 

repeat_time: 1
log_path: result
experiment_name: BNTTransformerExperiments
seed: 42

project: DLBenchmarking