defaults:
  - dataset: ABIDE  #ABIDE EOEC
  - model: mlp3hl # brainnetcnn, fbnetgen, bnt, transformer
  - optimizer: adam
  - training: basic_supervised #debug
  - datasz: 100p
  - preprocess: mlp_mixup #mlp_no_mixup

repeat_time: 5
log_path: result
experiment_name: MLP_ABIDE
seed: 42

project: DLBenchmarking